# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maestro2

on: [workflow_dispatch, push, pull_request]
env:
  JAVA_VERSION: 11.0.3
  SERVER_ID: snapshots



jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Maven Build
        run: mvn -B package --file pom.xml -DskipTests
      - name: Maven Test
        run: mvn test

